###Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3
###Authorization: Basic YWRtaW46YWRtaW4=
###Admin login
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###Create user for Itaration 2
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user7test",
  "password": "StrongPass77$7",
  "role": "USER"
}

###User login
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "username": "user7test",
  "password": "StrongPass77$7"

}

###Create the first account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

###Create the secont account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Deposit 250.5 account 1
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 250.5
}


###Positive test: Deposit 5000 account 1
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 5000
}

###Negative test: Deposit 5000.01
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 5000.01
}


###Negative test: Deposit cannot be less than 0
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": -1
}

###Positive test: Transfer money
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 250.75
}

###Positive test: Transfer money max sum 10000
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000
}

###Negative test: Transfer 0 money
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0
}


###Negative test: Deposit to non-existing account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 9999,
  "amount": 50.03
}


###Positive test : Get accounts transactions
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Get customer profile
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

###Positive test: Apdate customer profile
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "name": "John Smith"
}

###Negative test:One word name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "name": "Itan"
}


###Negative test: Numbers in name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "name": "Itan12345 Jonson"
}

###Negative test: Apdate customer profile without autorization
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json

{
  "name": "John Smith"
}