###Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3
###Authorization: Basic YWRtaW46YWRtaW4=
###Admin login
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


###Create user for Itaration 2
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user7test",
  "password": "StrongPass77$7",
  "role": "USER"
}


###User login
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "username": "user7test",
  "password": "StrongPass77$7"

}


###Create the first account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Create the secont account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Deposit 0.01 to account 1
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 0.01
}


###Positive test : Verify account transactions after depositing 0.01
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Deposit cannot be less than 0
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": -1
}

###Verify account transactions remain unchanged after failed deposit
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Deposit 250.01 to account 1
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 250.01
}


###Verify account transactions after depositing 250.01
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Deposit 4999.99 (boundary value)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 4999.99
}


###Verify account transactions after depositing 4999.99
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Deposit 5000 (maximum allowed value)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 5000
}


###Verify account transactions after depositing 5000
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Reject deposit greater than maximum (5000.01)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "id": 1,
  "balance": 5000.01
}


###Verify account transactions remain unchanged after failed deposit
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Transfer 0.01 from account 1 to account 2
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0.01
}


###Verify account transactions after transferring 0.01
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Reject transfer with amount 0
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0
}


###Verify account transactions remain unchanged after failed transfer
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test:Transfer 9999.99 (boundary value)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 9999.99
}


###Verify account transactions after transferring 9999.99
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


//Invalid transfer: insufficient funds or invalid accounts, response code  400
###Positive test: Transfer 10000 (maximum allowed amount)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000
}


###Verify account transactions after transferring 10000
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Reject transfer greater than maximum (10000.01)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000.01
}

###Verify account transactions remain unchanged after failed transfer
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Reject transfer to non-existing account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "senderAccountId": 1,
  "receiverAccountId": 9999,
  "amount": 50.03
}


###Verify account transactions remain unchanged after failed transfer
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Retrieve customer profile
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Positive test: Update customer profile
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "name": "John Smith"
}


###Verify customer profile after update
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Reject profile update with one-word name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "name": "Itan"
}


###Verify customer profile remains unchanged
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test:  Reject profile update with numbers in name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3

{
  "name": "Itan12345 Jonson"
}


###Verify customer profile remains unchanged
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3


###Negative test: Reject profile update without authorization
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json

{
  "name": "John Djill"
}


###Verify customer profile remains unchanged
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic dXNlcjd0ZXN0OlN0cm9uZ1Bhc3M3NyQ3